

x = {}
try:
    print(x[5])
except Exception as e:
    print("ERror", str(e))

